# Generated by Django 5.1.1 on 2025-10-06 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('requires_components', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'product_types',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('color_id', models.AutoField(primary_key=True, serialize=False)),
                ('color_name', models.CharField(max_length=30)),
                ('color_code', models.CharField(blank=True, max_length=10)),
                ('hex_value', models.CharField(blank=True, max_length=7)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.workspace')),
            ],
            options={
                'db_table': 'colors',
                'indexes': [models.Index(fields=['workspace', 'color_code'], name='colors_workspa_dc710b_idx')],
                'unique_together': {('workspace', 'color_name')},
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('material_id', models.AutoField(primary_key=True, serialize=False)),
                ('material_name', models.CharField(max_length=50)),
                ('material_code', models.CharField(blank=True, max_length=20)),
                ('cost_per_kg', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('density', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.workspace')),
            ],
            options={
                'db_table': 'materials',
                'indexes': [models.Index(fields=['workspace', 'material_code'], name='materials_workspa_6e6903_idx')],
                'unique_together': {('workspace', 'material_name')},
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('billbee_id', models.BigIntegerField(blank=True, null=True)),
                ('sku', models.CharField(blank=True, max_length=100, null=True)),
                ('ean', models.CharField(blank=True, max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_personalized', models.BooleanField(default=False)),
                ('pdf_fiche_technique', models.TextField(blank=True)),
                ('assembly_time_minutes', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.workspace')),
                ('product_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.producttype')),
            ],
            options={
                'db_table': 'products',
                'indexes': [models.Index(fields=['workspace', 'sku'], name='products_workspa_12e348_idx'), models.Index(fields=['workspace', 'ean'], name='products_workspa_5a269e_idx'), models.Index(fields=['product_type'], name='products_product_7a7b2f_idx')],
                'unique_together': {('workspace', 'sku')},
            },
        ),
    ]
