# Generated by Django 5.1.1 on 2025-10-06 12:36

import catalog.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDocument',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('spec', 'Spec / Fiche technique'), ('manual', 'Manual'), ('datasheet', 'Datasheet'), ('other', 'Other')], default='spec', max_length=20)),
                ('version', models.CharField(blank=True, max_length=50, null=True)),
                ('file', models.FileField(upload_to=catalog.models.product_doc_upload_to)),
                ('is_primary', models.BooleanField(default=False)),
                ('size', models.BigIntegerField(blank=True, null=True)),
                ('checksum', models.CharField(blank=True, max_length=64)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='catalog.product')),
            ],
            options={
                'db_table': 'product_documents',
                'indexes': [models.Index(fields=['product', 'kind'], name='product_doc_product_d5a8d6_idx'), models.Index(fields=['product', 'kind', 'version'], name='product_doc_product_d9721c_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('product', 'kind'), name='uniq_primary_doc_per_product_kind')],
                'unique_together': {('product', 'kind', 'version')},
            },
        ),
    ]
