# Generated by Django 5.1.1 on 2025-10-07 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_productdocument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pdf_fiche_technique',
        ),
    ]
