# Generated by Django 5.1.1 on 2025-10-07 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_product_pdf_fiche_technique'),
        ('core', '0003_alter_workspace_options_workspace_owner_and_more'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('order_number', models.CharField(max_length=50)),
                ('order_billbee_id', models.BigIntegerField(blank=True, null=True)),
                ('external_id', models.CharField(blank=True, max_length=120, null=True)),
                ('external_payload', models.JSONField(blank=True, null=True)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=100)),
                ('is_personalized', models.BooleanField(default=False)),
                ('shipping_address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('order_item_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('order_item_billbee_id', models.BigIntegerField(blank=True, null=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_personalized', models.BooleanField(default=False)),
                ('attributes', models.JSONField(blank=True, null=True)),
                ('external_id', models.CharField(blank=True, max_length=120, null=True)),
                ('external_payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'order_items',
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='external_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='external_payload',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['workspace', 'platform', 'external_id'], name='customers_workspa_c50ad8_idx'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id__isnull', False)), fields=('workspace', 'platform', 'external_id'), name='uniq_customer_external_when_present'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.customer'),
        ),
        migrations.AddField(
            model_name='order',
            name='platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.platformsource'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.orderstatus'),
        ),
        migrations.AddField(
            model_name='order',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.workspace'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.product'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer'], name='orders_custome_6c3a7f_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='orders_status__9aad55_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['platform'], name='orders_platfor_cdb4eb_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['paid_at'], name='orders_paid_at_882cb3_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['workspace', 'order_number'], name='orders_workspa_9023ad_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['workspace', 'platform', 'external_id'], name='orders_workspa_e4a66f_idx'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id__isnull', False)), fields=('workspace', 'platform', 'external_id'), name='uniq_order_external_when_present'),
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('workspace', 'order_number')},
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order'], name='order_items_order_i_26ad88_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['product'], name='order_items_product_a53db1_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['is_personalized'], name='order_items_is_pers_f135f2_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order', 'external_id'], name='order_items_order_i_68afe5_idx'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id__isnull', False)), fields=('order', 'external_id'), name='uniq_orderitem_external_when_present'),
        ),
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together={('order', 'product', 'is_personalized', 'attributes')},
        ),
    ]
