# Generated by Django 5.1.1 on 2025-10-07 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_product_pdf_fiche_technique'),
        ('orders', '0002_order_orderitem_customer_external_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='order',
            name='currency',
            field=models.CharField(default='TND', max_length=3),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='orderitem_qty_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 0), ('unit_price__isnull', True), _connector='OR'), name='orderitem_unit_price_gte_0'),
        ),
    ]
