# Generated by Django 5.1.1 on 2025-10-07 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_options_order_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='external_total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='totals_locked',
            field=models.BooleanField(default=False),
        ),
    ]
