# Generated by Django 5.1.1 on 2025-10-07 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_external_total_cost_order_totals_locked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='attributes',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
