# Generated by Django 5.1.1 on 2025-10-07 10:42

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0003_remove_product_pdf_fiche_technique'),
        ('core', '0003_alter_workspace_options_workspace_owner_and_more'),
        ('orders', '0005_alter_orderitem_attributes'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrinterType',
            fields=[
                ('printer_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('max_build_volume', models.CharField(blank=True, max_length=50)),
                ('supported_materials', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'printer_types',
                'ordering': ['type_name'],
            },
        ),
        migrations.CreateModel(
            name='Filament',
            fields=[
                ('filament_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('filament_name', models.CharField(max_length=100)),
                ('filament_code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('current_stock_grams', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('safety_stock_grams', models.DecimalField(decimal_places=3, default=Decimal('500'), max_digits=12)),
                ('reorder_point_grams', models.DecimalField(decimal_places=3, default=Decimal('1000'), max_digits=12)),
                ('cost_per_gram', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.color')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.material')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.workspace')),
            ],
            options={
                'db_table': 'filaments',
            },
        ),
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('printer_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('machine_name', models.CharField(max_length=100)),
                ('connection_type', models.CharField(default='WiFi', max_length=20)),
                ('printer_url', models.CharField(blank=True, max_length=255)),
                ('api_user', models.CharField(blank=True, max_length=100)),
                ('api_key', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('printing', 'Printing'), ('maintenance', 'Maintenance'), ('error', 'Error')], default='offline', max_length=20)),
                ('nozzle_temperature_max', models.IntegerField(default=300)),
                ('bed_temperature_max', models.IntegerField(default=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.workspace')),
                ('printer_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.printertype')),
            ],
            options={
                'db_table': 'printers',
            },
        ),
        migrations.CreateModel(
            name='PrintJob',
            fields=[
                ('print_job_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('component_label', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('printing', 'Printing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=12)),
                ('priority', models.IntegerField(default=1)),
                ('estimated_print_time', models.IntegerField(blank=True, null=True)),
                ('actual_print_time', models.IntegerField(blank=True, null=True)),
                ('material_used_grams', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filament_used', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.filament')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='print_jobs', to='orders.orderitem')),
                ('printer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.printer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.product')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.workspace')),
            ],
            options={
                'db_table': 'print_jobs',
                'ordering': ['status', '-priority', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='FilamentTransaction',
            fields=[
                ('transaction_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('in', 'In'), ('out', 'Out'), ('adjustment', 'Adjustment'), ('waste', 'Waste')], max_length=12)),
                ('quantity_grams', models.DecimalField(decimal_places=3, max_digits=12)),
                ('previous_stock', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('new_stock', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('filament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='production.filament')),
                ('print_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.printjob')),
            ],
            options={
                'db_table': 'filament_transactions',
            },
        ),
        migrations.AddIndex(
            model_name='filament',
            index=models.Index(fields=['workspace'], name='filaments_workspa_5c93d7_idx'),
        ),
        migrations.AddIndex(
            model_name='filament',
            index=models.Index(fields=['material', 'color'], name='filaments_materia_bfc8f9_idx'),
        ),
        migrations.AddIndex(
            model_name='filament',
            index=models.Index(fields=['is_available'], name='filaments_is_avai_200dfb_idx'),
        ),
        migrations.AddIndex(
            model_name='printer',
            index=models.Index(fields=['workspace'], name='printers_workspa_1427cc_idx'),
        ),
        migrations.AddIndex(
            model_name='printer',
            index=models.Index(fields=['status'], name='printers_status_24c88e_idx'),
        ),
        migrations.AddIndex(
            model_name='printer',
            index=models.Index(fields=['printer_type'], name='printers_printer_caf228_idx'),
        ),
        migrations.AddIndex(
            model_name='printjob',
            index=models.Index(fields=['workspace'], name='print_jobs_workspa_4bdbc2_idx'),
        ),
        migrations.AddIndex(
            model_name='printjob',
            index=models.Index(fields=['status'], name='print_jobs_status_4509dc_idx'),
        ),
        migrations.AddIndex(
            model_name='printjob',
            index=models.Index(fields=['priority'], name='print_jobs_priorit_1bac25_idx'),
        ),
        migrations.AddIndex(
            model_name='printjob',
            index=models.Index(fields=['printer'], name='print_jobs_printer_f459d2_idx'),
        ),
        migrations.AddIndex(
            model_name='filamenttransaction',
            index=models.Index(fields=['filament'], name='filament_tr_filamen_a181c6_idx'),
        ),
        migrations.AddIndex(
            model_name='filamenttransaction',
            index=models.Index(fields=['kind', 'created_at'], name='filament_tr_kind_71846e_idx'),
        ),
    ]
