# Generated by Django 5.1.1 on 2025-10-06 11:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def set_workspace_owner(apps, schema_editor):
    Workspace = apps.get_model("core", "Workspace")
    Membership = apps.get_model("core", "Membership")

    for workspace in Workspace.objects.filter(owner__isnull=True):
        owner_membership = (
            Membership.objects.filter(workspace=workspace, role="owner")
            .order_by("id")
            .first()
        )
        if owner_membership is None:
            owner_membership = (
                Membership.objects.filter(workspace=workspace)
                .order_by("id")
                .first()
            )
        if owner_membership is not None:
            workspace.owner_id = owner_membership.user_id
            workspace.save(update_fields=["owner"])


def unset_workspace_owner(apps, schema_editor):
    Workspace = apps.get_model("core", "Workspace")
    Workspace.objects.update(owner=None)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workspace',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='workspace',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_workspaces', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(set_workspace_owner, unset_workspace_owner),
        migrations.AlterField(
            model_name='workspace',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_workspaces', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
